export const END_LOADING = "END_LOADING"
export const START_LOADING = "START_LOADING"

export const CREATEUSERS = "CREATEUSERS";
export const FETCHUSERS = "FETCHUSERS"
export const UPDATEUSERS = "UPDATEUSERS"
export const DELETEUSERS = "DELETEUSERS"
export const FETCHSINGLEUSERS = "FETCHSINGLEUSERS"